Project1:对文件diabetes.csv中的数据进行处理，将文件夹pima-diabetes放在E：盘的input文件夹下

In [5]:
from pandas import *
import pandas as pd
import numpy as np
import seaborn as sns
from scipy.stats import mode

import os, sys
path = "/var/crash/www/"
dirs = os.listdir( path )

for file in dirs:
    print (file)

diabetes.csv

In [3]:
################################读入diabetes.csv文件到diabetes################################### 
diabetes = pd.read_csv('/var/crash/www/diabetes.csv')
################################读入diabetes.csv文件到diabetes###################################

In [4]:
################################显示diabetes的前5行################################### 
diabetes.head(5)
################################显示diabetes的前5行###################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Check for Summary Statistics

In [6]:
################################显示diabetes的详细信息，包括样本数、均值、方差等等################################## 
diabetes.describe()
################################显示diabetes的详细信息，包括样本数、均值、方差等等##################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [7]:
################################显示diabetes中Outcome列中每种值出现的次数################################## 
diabetes["Outcome"].value_counts()
################################显示diabetes中Outcome列中每种值出现的次数##################################

0    500
1    268
Name: Outcome, dtype: int64

### Check missing values

In [6]:
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
################################显示diabetes中所有列的标题名################################## 
diabetes.columns
################################显示diabetes中所有列的标题名##################################

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [8]:
################################显示diabetes中所有列的值里面为0的个数################################## 
print((diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']] == 0).sum())
################################显示diabetes中所有列的值里面为0的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
dtype: int64

In [8]:
################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.loc[:,['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']] = diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']].replace(0, np.NaN)

################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,NaN,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [9]:
################################统计diabetes中所有列的值中为null的个数################################## 
diabetes.isnull().sum()
################################统计diabetes中所有列的值中为null的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

## Dealing with missing values

## A. Drop rows having NaN

In [10]:
print("Size before dropping NaN rows",diabetes.shape,"\n")

################################将diabetes中包含NaN的行删掉################################## 
nan_dropped = diabetes.dropna()
################################将diabetes中包含NaN的行删掉################################## 
print(nan_dropped.isnull().sum())
print("\nSize after dropping NaN rows",nan_dropped.shape)

Size before dropping NaN rows (768, 9)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Size after dropping NaN rows (336, 9)

### **Project2、数据分析的一系列问题**

In [11]:
vector = np.random.chisquare(1,500)
print(vector)
################################打印vector的均值################################## 
print("Mean",np.mean(vector))
################################打印vector的均值################################## 

print("SD",np.std(vector))
print("Range",max(vector)-min(vector))

[2.14745931e+00 2.04699024e-01 1.26512016e+00 6.82825082e-01
 2.78954344e+00 1.12185926e-01 1.02493629e+00 8.45675713e-01
 5.66756734e-02 2.20248812e-02 5.88377708e-01 5.10445600e-01
 8.51969127e+00 3.95920820e+00 9.53898170e+00 1.77544156e-04
 7.61414185e-01 9.33187510e-01 1.18111828e-02 4.88665308e+00
 3.12713322e+00 3.96589131e-02 2.86215675e-01 7.02275372e+00
 4.69451844e-01 4.97647022e-02 1.02408671e+01 1.29284672e+00
 3.73373935e-01 4.56956739e-03 8.89260596e-01 2.77865085e-01
 3.65036097e+00 1.18619444e+00 1.18428980e+00 1.79054808e+00
 1.21116537e+00 8.26176516e-03 3.39593032e-01 1.65673832e-01
 2.83110120e-05 7.95691512e-01 7.43728789e-01 4.13964148e-01
 1.53339442e-03 8.31266502e-04 2.06956447e-03 2.06593642e-02
 3.74949995e+00 1.21081043e-01 5.35692570e-02 1.77995062e+00
 3.48335822e+00 8.89606537e+00 1.02368406e+00 2.38009555e+00
 1.30785652e-01 1.48290236e-01 3.49235999e-01 5.90337259e-01
 1.90225562e-02 3.14483427e+00 5.45796453e-01 3.11647196e-01
 1.12961535e+00 6.03708523e-01 4.40003851e+00 3.50419228e-01
 6.71678329e-01 1.54172946e-02 4.40966915e-02 3.19382696e-01
 2.53246293e+00 1.20017558e+00 1.57508039e+00 7.58374516e-01
 1.81806438e+00 8.22247215e-01 2.39294316e+00 6.37228717e-02
 6.49455916e-01 2.02614815e-04 1.89760327e+00 3.34365436e+00
 1.81022108e+00 1.93165563e+00 1.25956981e+00 3.63867018e-01
 1.29610629e+00 7.17973856e-02 9.80371590e-02 3.82273841e-04
 2.11096217e+00 2.36724355e+00 3.45763167e+00 4.29575832e-01
 2.09674729e-01 5.95511315e-01 7.00462784e-01 5.48121035e+00
 1.11789402e+00 1.59254850e-01 1.25648562e-01 4.26200797e-01
 2.39512202e+00 6.06383797e-01 6.62458864e-01 1.69209907e+00
 1.67399694e-01 2.44887601e+00 2.70513225e+00 7.13882758e+00
 4.04127073e-02 3.16699764e+00 2.41347416e+00 1.02417493e-01
 1.17789297e+00 5.67208463e-01 1.61483425e+00 2.39572780e-01
 2.56852145e-01 1.10129309e+00 3.00029838e-01 5.38789244e+00
 2.42628596e-01 2.24284666e+00 7.24864612e-01 1.58851126e+00
 6.56622233e-02 1.80845728e+00 1.00887545e+00 7.64595459e-04
 4.05431021e-02 2.74380990e-01 4.81982892e+00 5.00336653e+00
 1.00757216e+00 1.70353784e-03 1.71147898e-01 5.74081725e-01
 3.47011425e-03 1.08730530e+00 3.46258822e+00 1.36357284e-01
 4.63743471e-01 6.99847151e-01 3.81266938e-01 2.98967052e+00
 1.64183406e-01 4.58797360e-01 9.45455098e-01 1.58855682e+00
 3.46429504e-01 3.10289596e-01 4.84521025e+00 2.15386787e+00
 2.41537238e-01 2.43380978e-01 4.13546116e-02 2.44930396e-02
 1.42935700e+00 2.73238719e-01 4.66256495e-03 3.91064521e-01
 1.47820521e+00 8.54771318e-01 3.84778967e-01 1.24820793e+00
 5.63491070e-01 4.79553887e-02 3.88525650e-02 7.19660139e-01
 3.00312625e-01 7.27154734e-03 1.48819730e-01 5.62841233e-01
 2.26790115e-02 2.26765732e+00 3.60053769e-01 8.84986115e-02
 1.16544711e-03 1.15879406e+00 7.81209079e-03 1.42356910e-01
 1.42384397e+00 1.45491595e+00 1.22905366e+00 1.53386035e-01
 2.73853016e-01 2.73789555e-01 1.97040087e-02 7.60681710e-02
 1.81930698e-02 1.50391771e+00 1.01682596e-01 2.76146060e+00
 2.81076680e-01 1.26198096e+00 3.66786400e-01 7.96831412e-01
 3.35465371e-01 9.79686149e-01 8.04356769e-01 7.36856052e-01
 2.30249554e-01 6.85982366e-02 1.85692625e+00 1.91290384e-01
 1.27988593e-01 5.09059256e-01 8.19602514e-01 1.00592941e+00
 6.07291890e-03 6.28380375e-01 2.17018297e+00 1.41247331e-01
 2.44552319e-01 2.25098697e+00 1.43002493e-01 2.12505103e-01
 1.64463588e+00 1.81754592e+00 1.11845993e-02 2.83769383e-01
 1.30106422e+00 1.60634173e+00 1.73974702e+00 3.28683078e+00
 6.57873609e-02 1.09454064e-03 7.21900553e-03 5.94969952e-02
 2.48710950e-01 1.99562967e+00 1.95758580e-01 7.90716166e-01
 2.75793224e+00 4.46336468e-01 3.08266660e-01 1.67928490e+00
 3.71189731e-01 2.86987091e+00 3.65495145e+00 6.09205989e-01
 1.37561319e+00 7.79286246e-01 9.02653465e-03 5.78514794e-03
 1.13612294e+00 4.68555404e-01 3.31741757e-02 8.41502654e-01
 4.77026815e-01 6.74674485e-02 1.37366890e-01 2.87844678e-01
 3.97423454e+00 5.81345037e-01 6.34956020e-01 2.91037776e+00
 3.09412332e-01 3.05374130e+00 9.78204083e-01 3.48412457e-01
 1.41516593e-01 1.29555203e+00 4.12517114e-02 2.23643015e+00
 1.25109704e+00 5.21250639e-01 1.94616558e-01 6.06877004e+00
 1.26739682e+00 7.37885399e-03 1.04327113e+00 6.24705316e-01
 5.71949177e-02 4.10386803e+00 4.58030569e-01 3.25299511e+00
 2.09742791e+00 1.26801601e+00 3.28859128e-01 3.88492126e-01
 6.35310447e-03 2.23244921e+00 1.06768630e+00 1.08781528e-01
 1.53574577e+00 9.40910897e-02 2.12563935e+00 1.30487366e-01
 2.71047910e-01 3.63055050e-02 1.90781396e+00 2.39464579e-02
 9.21881598e+00 2.14707924e-01 3.10650933e+00 3.34106118e+00
 1.91458555e+00 2.36050088e-01 6.51246888e-02 3.22549787e-01
 4.51109946e+00 5.01976664e-01 7.60655261e-01 3.23817945e+00
 6.44026896e-03 5.34078276e-03 3.14590900e-04 1.22288669e-01
 6.04324269e-01 2.46475763e-01 3.41139064e+00 2.51474780e-01
 9.95466839e-03 1.27258029e+00 2.66627771e-01 3.74865022e+00
 2.35208005e-01 1.48809984e+00 2.56574271e-01 3.34392371e-01
 1.11426554e+00 1.47486239e+00 1.70958191e+00 7.39624989e-01
 6.90591846e-01 3.58488338e+00 4.55730309e-03 4.18797801e-02
 1.57106808e+00 5.11310848e-02 1.21373936e-03 1.43449351e+00
 2.49200148e-01 3.25732229e+00 3.57052312e-01 4.01856482e+00
 2.07010387e-01 2.86216160e+00 9.05685764e-02 5.86149541e-01
 7.43907316e-01 2.00125205e-01 7.05152579e-01 2.84472604e-02
 1.09847475e+00 1.32607320e-01 1.81619933e-01 7.18820750e-01
 7.30874236e-01 3.53738886e-02 1.38356975e+00 2.62019913e+00
 3.23614646e-02 3.72388625e-01 1.70475020e-01 2.41864264e-01
 1.12788560e-02 6.65024136e-02 2.17377356e+00 4.19818927e-01
 1.39942559e+00 3.59180867e+00 4.06941412e-01 1.37506486e+00
 9.16247932e-01 1.87526958e+00 2.28425841e-01 2.33807831e+00
 2.61016630e+00 1.33715901e-01 3.41710976e-01 2.27776923e+00
 2.80044762e+00 1.17069912e-01 1.20693581e+00 9.26373432e-01
 9.16964273e-01 2.57601955e+00 8.68536039e-01 7.69657212e-02
 5.05675818e-01 6.19876351e-02 1.28390517e-01 2.75135630e-03
 9.39581834e-02 5.49499768e-01 2.99832340e+00 4.41973944e-01
 5.86132450e-01 9.65903507e-01 2.12767220e+00 1.91402522e-02
 1.51205494e-01 5.96174930e-01 8.14015155e-02 2.96229218e-02
 5.03049098e+00 3.01374989e-03 5.20616691e-01 2.22339236e+00
 1.38506049e-02 3.29777872e+00 1.81238511e-02 9.46123965e-01
 1.96825826e-05 1.19562835e+00 1.85224369e+00 4.26807033e-01
 5.12144308e-01 1.09130135e+00 2.74157920e-01 4.20826266e-02
 6.55237966e-01 1.92066569e-01 1.42260602e+00 8.78157483e-03
 6.60775883e-01 8.09979306e-03 4.53332053e-01 4.23631837e+00
 1.01649538e-01 4.88701818e+00 1.20582028e+00 2.89040611e-01
 2.97676490e-01 1.76089779e-01 9.08806805e-01 6.24219614e-03
 1.19812421e-01 2.18536555e-01 1.41671270e-01 2.78047200e-01
 2.57687965e-01 9.31433307e-04 3.65948514e-01 2.48685814e-01
 1.26040680e+00 8.75703686e-07 5.40006960e-01 2.25320365e-01
 1.44852169e-03 5.93139361e+00 3.90832335e+00 3.19841265e-01
 9.93624338e-01 3.28968566e-02 2.74884893e-01 1.45210857e-01
 4.36778153e-01 1.33969133e-01 3.85983306e-02 2.31820280e-01
 1.19141185e+00 4.23396781e-02 1.20141982e+00 3.00303693e+00
 1.17479054e-01 6.20190500e-01 4.92583936e-03 1.56782083e-01
 1.24707779e+00 8.65335499e-02 5.52605946e-01 7.98005663e-02
 7.71998600e-01 3.37848034e-01 8.37501258e-01 3.68165230e+00
 2.57414273e-01 2.65991954e-01 2.02498940e+00 6.58330463e-03
 6.60133117e-01 4.31036970e-01 1.06616799e+00 6.85957628e-01
 5.20446654e-02 1.81500938e+00 7.01845987e-03 1.19774418e+00
 2.17264544e+00 1.10251935e-01 9.03413086e-01 7.09275119e-01
 6.70531261e-01 3.72444673e-02 1.02831906e-02 1.04659092e-02
 1.90386090e+00 6.78323339e-04 6.17541707e-01 1.17846052e-01
 1.19488971e-01 3.43482888e-04 7.52684472e-01 1.06261913e+00]
Mean 1.0744654606773028
SD 1.484493082667475
Range 10.240866235474181

### Reshape

In [18]:
vector.shape

(500,)

In [19]:
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector = vector.reshape(-1,1)
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector.shape
print(row_vector)

[[3.95924558e-02]
 [1.08486518e-03]
 [2.48813284e-01]
 [3.29204594e-02]
 [3.25463758e-01]
 [1.02977100e+00]
 [7.00744235e-01]
 [7.22577432e-01]
 [1.28129213e+00]
 [8.93506738e-02]
 [3.29226570e-01]
 [2.34269184e+00]
 [6.60563372e-01]
 [3.42539743e-01]
 [6.77953082e-02]
 [8.85047100e-01]
 [1.06394441e+00]
 [6.38962327e-02]
 [2.12703849e-01]
 [3.71060152e+00]
 [9.88882618e-01]
 [4.72865176e-01]
 [9.99455765e+00]
 [3.10717801e-01]
 [2.93864073e-01]
 [1.53213352e-01]
 [6.28697380e-01]
 [5.00196605e-03]
 [1.37777031e+00]
 [6.99231813e-01]
 [6.26069550e+00]
 [1.01180456e-01]
 [7.78422371e-01]
 [4.52861004e-02]
 [3.50603341e-01]
 [2.46281508e-01]
 [1.48241707e-01]
 [9.55821688e-01]
 [2.45670769e-01]
 [4.62350293e-01]
 [2.06126726e+00]
 [9.08804346e-01]
 [1.25759670e+00]
 [2.82936053e+00]
 [1.03035727e+01]
 [6.56165761e-01]
 [1.20064356e+00]
 [1.28084307e+00]
 [6.48149261e-01]
 [6.15119639e-02]
 [3.74865370e-01]
 [1.18755738e-01]
 [3.65960757e-01]
 [4.97218707e-01]
 [9.37703001e-02]
 [1.49394903e-01]
 [2.05809936e+00]
 [1.62816646e+00]
 [4.70577273e-03]
 [2.64094619e+00]
 [4.64250296e-01]
 [8.87203257e-01]
 [9.49421051e-02]
 [5.71397255e-01]
 [3.09903622e+00]
 [7.83958490e+00]
 [1.13358641e+00]
 [1.64633229e-01]
 [1.69846050e-02]
 [1.47757687e-02]
 [1.47440318e+00]
 [2.92158543e-01]
 [1.99941712e-01]
 [8.77696197e-01]
 [2.34471657e-03]
 [2.43423273e-01]
 [3.05626953e-01]
 [1.21205678e+00]
 [6.98832265e-02]
 [1.30913211e-01]
 [1.97908819e-01]
 [3.44891994e-01]
 [6.09555416e-02]
 [1.18697903e+00]
 [1.37813418e+00]
 [2.22814026e-02]
 [3.67732145e-01]
 [7.81412074e-02]
 [6.42306245e-01]
 [1.95420851e+00]
 [9.67779290e-01]
 [5.67577859e-06]
 [1.19927428e-02]
 [3.78530706e-04]
 [9.37852458e-01]
 [1.00512417e-02]
 [1.15297296e-01]
 [1.94432251e+00]
 [9.71432630e-02]
 [3.07327625e-02]
 [1.04155166e-01]
 [2.08362846e-01]
 [6.98989178e-02]
 [9.85966559e-01]
 [1.00743523e+00]
 [9.69910034e-02]
 [9.54124222e-01]
 [2.78055647e+00]
 [3.11610149e-02]
 [9.06007796e-01]
 [1.08511438e+00]
 [1.55229613e-02]
 [9.43430423e-01]
 [4.11667792e-01]
 [8.14202369e-01]
 [5.24612675e-02]
 [3.00843823e+00]
 [1.02102213e-01]
 [1.22338847e+00]
 [5.66834841e+00]
 [2.73892973e+00]
 [8.39216039e-01]
 [2.79955175e+00]
 [2.74542520e-03]
 [7.99173158e-01]
 [3.41194752e-01]
 [2.46382288e+00]
 [1.89836648e-01]
 [1.91219537e+00]
 [2.49191356e-02]
 [2.73887951e-02]
 [2.74517456e-01]
 [1.20762328e+00]
 [1.30677568e-01]
 [1.87206125e+00]
 [8.71417470e-05]
 [7.79474412e-01]
 [7.45509474e-01]
 [3.89333866e-01]
 [3.52511681e-01]
 [3.06857771e-01]
 [2.94558004e-01]
 [5.50665622e-03]
 [1.66723457e+00]
 [2.80765193e+00]
 [4.73921953e-02]
 [3.18285743e+00]
 [6.61911419e-02]
 [2.53619235e+00]
 [1.28881112e-01]
 [4.32966365e+00]
 [1.30642988e-03]
 [1.58221407e+00]
 [1.36615155e+00]
 [5.64489550e+00]
 [8.22943445e-02]
 [2.01557318e+00]
 [5.88828748e-04]
 [3.51392928e-01]
 [1.53707381e+00]
 [4.70894481e-01]
 [1.70414863e-02]
 [1.63206265e+00]
 [3.48527760e-01]
 [4.28766168e-01]
 [1.61142741e-02]
 [6.31921686e-02]
 [2.65207894e-01]
 [2.64820016e-04]
 [9.85515941e-03]
 [2.47678272e+00]
 [9.04641712e-03]
 [1.11628090e+00]
 [4.47658396e-01]
 [2.16182283e+00]
 [4.54623130e+00]
 [7.97561634e+00]
 [5.74787996e-01]
 [1.35646628e+00]
 [6.93453938e-01]
 [7.53817859e-01]
 [2.41135908e+00]
 [4.38836409e+00]
 [1.34699517e-01]
 [2.45611923e+00]
 [2.30676107e-01]
 [2.44687679e+00]
 [4.53680644e-01]
 [8.33535402e-01]
 [2.44155429e+00]
 [2.67243735e-01]
 [1.46276026e+00]
 [3.68987003e-01]
 [1.16385964e+00]
 [2.49343442e-01]
 [9.79490907e-02]
 [8.94243650e-01]
 [2.83499915e-03]
 [4.94052561e+00]
 [4.88387244e-01]
 [2.18902476e-01]
 [2.06674200e-02]
 [1.83421586e-01]
 [4.89736283e-01]
 [1.34395527e+00]
 [2.73092152e-04]
 [1.14036101e+00]
 [3.70692862e+00]
 [1.16160611e-01]
 [4.46914925e-02]
 [1.31153956e+00]
 [7.96010997e-01]
 [2.27357683e+00]
 [1.38232538e+00]
 [3.72201840e+00]
 [4.19292801e-01]
 [3.06041376e-04]
 [3.32355977e-01]
 [2.75827051e-01]
 [3.15017858e-02]
 [7.19376758e-01]
 [1.66702555e-01]
 [3.15909072e+00]
 [8.11550865e-01]
 [1.03953691e+00]
 [1.09004894e-01]
 [1.30248345e-01]
 [4.08847357e-01]
 [1.31361087e+00]
 [3.00968575e+00]
 [4.77634139e+00]
 [1.15166487e+00]
 [3.70152174e-02]
 [2.60485663e-02]
 [4.84639328e-01]
 [6.37390429e-02]
 [5.17719114e+00]
 [1.59253680e+00]
 [1.09428393e+00]
 [1.10188299e+00]
 [6.13927316e-02]
 [2.34915479e-01]
 [3.00082790e+00]
 [2.06213901e+00]
 [5.19262474e-01]
 [4.63822682e-01]
 [2.96963412e+00]
 [2.17694805e-01]
 [1.63096865e+00]
 [1.20291645e+00]
 [7.97989545e-01]
 [7.47625223e-01]
 [4.23798144e-01]
 [4.45121964e-01]
 [3.72724821e+00]
 [7.15299254e-01]
 [1.74478318e+00]
 [7.09592458e-03]
 [1.53506403e-01]
 [1.11610548e+00]
 [5.23930767e-04]
 [1.38139293e+00]
 [5.60412726e-02]
 [3.78635832e-01]
 [1.24378830e-01]
 [4.90383966e-05]
 [9.72774975e-01]
 [1.12155602e-03]
 [5.22259331e-01]
 [3.11791505e-01]
 [3.95724466e-02]
 [2.58947046e-01]
 [3.75732481e-01]
 [4.08803468e+00]
 [3.47683272e-01]
 [4.70291615e-01]
 [2.12897896e-02]
 [1.02516251e-01]
 [4.11495729e+00]
 [8.53733049e-01]
 [4.17608039e-02]
 [1.64583289e-01]
 [1.09176844e-01]
 [6.40630464e-01]
 [6.63804799e-01]
 [1.42478674e+00]
 [2.65835595e+00]
 [3.71531075e-01]
 [5.02672562e+00]
 [1.43047281e-02]
 [3.27382451e-01]
 [7.30912530e-01]
 [4.14632429e-01]
 [3.20346820e-05]
 [7.01957290e-02]
 [2.07998361e-01]
 [5.05196188e+00]
 [4.60501671e+00]
 [1.75777415e-01]
 [6.98172112e-01]
 [3.31111147e-02]
 [1.84839146e+00]
 [2.56943103e+00]
 [2.80770087e+00]
 [2.37746050e+00]
 [1.05717308e+00]
 [5.91082753e-01]
 [2.65849471e-01]
 [2.18576854e-01]
 [5.31312270e-01]
 [1.81284039e+00]
 [2.46978393e-01]
 [2.12618395e-01]
 [1.06366720e-01]
 [7.29181474e-02]
 [4.70330142e-02]
 [6.14606088e-02]
 [2.17760877e-01]
 [1.15166774e-01]
 [3.50974895e-01]
 [4.86139668e-01]
 [7.15656098e-03]
 [4.51475448e-02]
 [1.06350247e-01]
 [4.62522219e+00]
 [9.86053275e-01]
 [1.07425598e-01]
 [1.66841282e-01]
 [2.53121290e-02]
 [1.30133420e+00]
 [2.52702812e+00]
 [1.70731734e+00]
 [1.23038972e-01]
 [3.63864711e+00]
 [7.97320761e-01]
 [8.36585523e-03]
 [1.25609557e-01]
 [4.10859457e-01]
 [5.47311400e-02]
 [1.13321720e+00]
 [1.59894462e-02]
 [6.37079695e-02]
 [1.30128664e-02]
 [2.21370966e+00]
 [1.33034942e+00]
 [2.64226527e+00]
 [5.11113619e-01]
 [3.91517011e+00]
 [9.00368734e-01]
 [2.72254224e-03]
 [1.13763442e-01]
 [2.95324275e-01]
 [8.85063034e-01]
 [8.40939340e-01]
 [1.30438706e-01]
 [5.72368907e-02]
 [3.24768261e-01]
 [2.62644738e+00]
 [4.06193747e-01]
 [2.25075145e-05]
 [6.27488227e-01]
 [4.61225118e-02]
 [7.40402280e-04]
 [1.81992500e-03]
 [4.22017694e-01]
 [3.48103117e-01]
 [3.23809725e-01]
 [1.74692107e-03]
 [1.27122411e+00]
 [6.12171318e-01]
 [7.81421756e-03]
 [3.52374067e-01]
 [5.87755307e-01]
 [6.22980732e-02]
 [9.96518864e-02]
 [5.75351455e-01]
 [1.73925852e-01]
 [3.59836284e-01]
 [2.18080457e-02]
 [2.53447264e+00]
 [6.50047674e-01]
 [1.32366997e+00]
 [1.09163759e-01]
 [6.44057295e-02]
 [6.27233588e-01]
 [4.64281849e-01]
 [4.91216088e-01]
 [1.92032666e-01]
 [6.61409943e-01]
 [1.63723468e+00]
 [1.77596758e-01]
 [3.63199601e-02]
 [1.85092062e+00]
 [5.18187453e-01]
 [5.30054644e-02]
 [4.10337340e-02]
 [1.87881797e+00]
 [3.49843270e+00]
 [9.46209998e-01]
 [6.25471786e-01]
 [4.32128944e-01]
 [5.24163468e-02]
 [1.26091871e-03]
 [1.31414018e+00]
 [1.59969222e+00]
 [5.06350489e-02]
 [4.94670227e-01]
 [1.11971020e-02]
 [2.94171092e-01]
 [7.56058178e+00]
 [9.24615803e-01]
 [7.67438699e-02]
 [4.10271006e+00]
 [3.47582109e+00]
 [5.87543585e-01]
 [1.94171522e-02]
 [3.17931897e-01]
 [3.79637910e-01]
 [4.89337299e-01]
 [5.32797927e-01]
 [2.58051089e+00]
 [1.50310595e-01]
 [1.36771210e-01]
 [4.01581205e-02]
 [6.61506761e+00]
 [4.54675893e-01]
 [1.08401091e+00]
 [9.42933866e-02]
 [1.75265998e-02]
 [4.48043797e-02]
 [5.92443565e-01]
 [9.03813435e-01]
 [9.77822483e-03]
 [7.48942235e+00]
 [4.90212398e-01]
 [7.83478607e-03]
 [1.75818552e+00]
 [1.58269958e-01]
 [5.23542980e-03]
 [5.42442925e+00]
 [4.24279579e+00]
 [3.54749817e-01]
 [1.60039880e-01]
 [3.35512448e-01]
 [2.17713093e-01]
 [9.07988122e-04]
 [1.56340883e-02]
 [3.08384052e-02]
 [2.92286337e-01]
 [2.32855375e-01]
 [4.13691400e-01]
 [8.96031801e-02]
 [3.50869476e+00]
 [3.95854862e-01]
 [6.34320160e-01]
 [3.38766778e+00]
 [1.13928407e+00]
 [3.82440545e-01]
 [4.94878542e-01]
 [8.38569073e-01]
 [4.95812957e-02]
 [2.99687449e+00]
 [2.12962004e-01]
 [6.58473820e-02]
 [1.79110598e+00]
 [2.06527610e-03]
 [2.76396719e+00]
 [8.85249118e-01]
 [1.51061139e+00]
 [1.21540605e+00]
 [3.28316926e-02]
 [4.52876565e-02]
 [4.30046574e+00]
 [1.49846408e-01]
 [2.00557945e+00]
 [4.65564975e-01]
 [1.81167688e-02]
 [4.95760634e-01]
 [1.85424667e-02]
 [1.41702939e-02]
 [4.73558415e-01]
 [7.61499763e-03]
 [5.47800391e-01]
 [2.73394508e+00]
 [2.82836592e+00]
 [1.16280931e-01]
 [2.50806777e-03]
 [2.03708624e-02]
 [8.31615396e-01]
 [2.27190928e+00]
 [2.44710189e+00]
 [1.70031844e-02]
 [1.54732595e-01]
 [1.81142483e-01]
 [3.40560602e-01]
 [4.37149694e-02]
 [6.83096839e-01]
 [2.97176088e-01]
 [1.94670232e-01]
 [3.04163480e+00]]

In [15]:
col_vector = vector.reshape(1,-1)
col_vector.shape

(1, 500)

In [20]:
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix = vector.reshape(10,50)
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix.shape
print(matrix)

[[3.95924558e-02 1.08486518e-03 2.48813284e-01 3.29204594e-02
  3.25463758e-01 1.02977100e+00 7.00744235e-01 7.22577432e-01
  1.28129213e+00 8.93506738e-02 3.29226570e-01 2.34269184e+00
  6.60563372e-01 3.42539743e-01 6.77953082e-02 8.85047100e-01
  1.06394441e+00 6.38962327e-02 2.12703849e-01 3.71060152e+00
  9.88882618e-01 4.72865176e-01 9.99455765e+00 3.10717801e-01
  2.93864073e-01 1.53213352e-01 6.28697380e-01 5.00196605e-03
  1.37777031e+00 6.99231813e-01 6.26069550e+00 1.01180456e-01
  7.78422371e-01 4.52861004e-02 3.50603341e-01 2.46281508e-01
  1.48241707e-01 9.55821688e-01 2.45670769e-01 4.62350293e-01
  2.06126726e+00 9.08804346e-01 1.25759670e+00 2.82936053e+00
  1.03035727e+01 6.56165761e-01 1.20064356e+00 1.28084307e+00
  6.48149261e-01 6.15119639e-02]
 [3.74865370e-01 1.18755738e-01 3.65960757e-01 4.97218707e-01
  9.37703001e-02 1.49394903e-01 2.05809936e+00 1.62816646e+00
  4.70577273e-03 2.64094619e+00 4.64250296e-01 8.87203257e-01
  9.49421051e-02 5.71397255e-01 3.09903622e+00 7.83958490e+00
  1.13358641e+00 1.64633229e-01 1.69846050e-02 1.47757687e-02
  1.47440318e+00 2.92158543e-01 1.99941712e-01 8.77696197e-01
  2.34471657e-03 2.43423273e-01 3.05626953e-01 1.21205678e+00
  6.98832265e-02 1.30913211e-01 1.97908819e-01 3.44891994e-01
  6.09555416e-02 1.18697903e+00 1.37813418e+00 2.22814026e-02
  3.67732145e-01 7.81412074e-02 6.42306245e-01 1.95420851e+00
  9.67779290e-01 5.67577859e-06 1.19927428e-02 3.78530706e-04
  9.37852458e-01 1.00512417e-02 1.15297296e-01 1.94432251e+00
  9.71432630e-02 3.07327625e-02]
 [1.04155166e-01 2.08362846e-01 6.98989178e-02 9.85966559e-01
  1.00743523e+00 9.69910034e-02 9.54124222e-01 2.78055647e+00
  3.11610149e-02 9.06007796e-01 1.08511438e+00 1.55229613e-02
  9.43430423e-01 4.11667792e-01 8.14202369e-01 5.24612675e-02
  3.00843823e+00 1.02102213e-01 1.22338847e+00 5.66834841e+00
  2.73892973e+00 8.39216039e-01 2.79955175e+00 2.74542520e-03
  7.99173158e-01 3.41194752e-01 2.46382288e+00 1.89836648e-01
  1.91219537e+00 2.49191356e-02 2.73887951e-02 2.74517456e-01
  1.20762328e+00 1.30677568e-01 1.87206125e+00 8.71417470e-05
  7.79474412e-01 7.45509474e-01 3.89333866e-01 3.52511681e-01
  3.06857771e-01 2.94558004e-01 5.50665622e-03 1.66723457e+00
  2.80765193e+00 4.73921953e-02 3.18285743e+00 6.61911419e-02
  2.53619235e+00 1.28881112e-01]
 [4.32966365e+00 1.30642988e-03 1.58221407e+00 1.36615155e+00
  5.64489550e+00 8.22943445e-02 2.01557318e+00 5.88828748e-04
  3.51392928e-01 1.53707381e+00 4.70894481e-01 1.70414863e-02
  1.63206265e+00 3.48527760e-01 4.28766168e-01 1.61142741e-02
  6.31921686e-02 2.65207894e-01 2.64820016e-04 9.85515941e-03
  2.47678272e+00 9.04641712e-03 1.11628090e+00 4.47658396e-01
  2.16182283e+00 4.54623130e+00 7.97561634e+00 5.74787996e-01
  1.35646628e+00 6.93453938e-01 7.53817859e-01 2.41135908e+00
  4.38836409e+00 1.34699517e-01 2.45611923e+00 2.30676107e-01
  2.44687679e+00 4.53680644e-01 8.33535402e-01 2.44155429e+00
  2.67243735e-01 1.46276026e+00 3.68987003e-01 1.16385964e+00
  2.49343442e-01 9.79490907e-02 8.94243650e-01 2.83499915e-03
  4.94052561e+00 4.88387244e-01]
 [2.18902476e-01 2.06674200e-02 1.83421586e-01 4.89736283e-01
  1.34395527e+00 2.73092152e-04 1.14036101e+00 3.70692862e+00
  1.16160611e-01 4.46914925e-02 1.31153956e+00 7.96010997e-01
  2.27357683e+00 1.38232538e+00 3.72201840e+00 4.19292801e-01
  3.06041376e-04 3.32355977e-01 2.75827051e-01 3.15017858e-02
  7.19376758e-01 1.66702555e-01 3.15909072e+00 8.11550865e-01
  1.03953691e+00 1.09004894e-01 1.30248345e-01 4.08847357e-01
  1.31361087e+00 3.00968575e+00 4.77634139e+00 1.15166487e+00
  3.70152174e-02 2.60485663e-02 4.84639328e-01 6.37390429e-02
  5.17719114e+00 1.59253680e+00 1.09428393e+00 1.10188299e+00
  6.13927316e-02 2.34915479e-01 3.00082790e+00 2.06213901e+00
  5.19262474e-01 4.63822682e-01 2.96963412e+00 2.17694805e-01
  1.63096865e+00 1.20291645e+00]
 [7.97989545e-01 7.47625223e-01 4.23798144e-01 4.45121964e-01
  3.72724821e+00 7.15299254e-01 1.74478318e+00 7.09592458e-03
  1.53506403e-01 1.11610548e+00 5.23930767e-04 1.38139293e+00
  5.60412726e-02 3.78635832e-01 1.24378830e-01 4.90383966e-05
  9.72774975e-01 1.12155602e-03 5.22259331e-01 3.11791505e-01
  3.95724466e-02 2.58947046e-01 3.75732481e-01 4.08803468e+00
  3.47683272e-01 4.70291615e-01 2.12897896e-02 1.02516251e-01
  4.11495729e+00 8.53733049e-01 4.17608039e-02 1.64583289e-01
  1.09176844e-01 6.40630464e-01 6.63804799e-01 1.42478674e+00
  2.65835595e+00 3.71531075e-01 5.02672562e+00 1.43047281e-02
  3.27382451e-01 7.30912530e-01 4.14632429e-01 3.20346820e-05
  7.01957290e-02 2.07998361e-01 5.05196188e+00 4.60501671e+00
  1.75777415e-01 6.98172112e-01]
 [3.31111147e-02 1.84839146e+00 2.56943103e+00 2.80770087e+00
  2.37746050e+00 1.05717308e+00 5.91082753e-01 2.65849471e-01
  2.18576854e-01 5.31312270e-01 1.81284039e+00 2.46978393e-01
  2.12618395e-01 1.06366720e-01 7.29181474e-02 4.70330142e-02
  6.14606088e-02 2.17760877e-01 1.15166774e-01 3.50974895e-01
  4.86139668e-01 7.15656098e-03 4.51475448e-02 1.06350247e-01
  4.62522219e+00 9.86053275e-01 1.07425598e-01 1.66841282e-01
  2.53121290e-02 1.30133420e+00 2.52702812e+00 1.70731734e+00
  1.23038972e-01 3.63864711e+00 7.97320761e-01 8.36585523e-03
  1.25609557e-01 4.10859457e-01 5.47311400e-02 1.13321720e+00
  1.59894462e-02 6.37079695e-02 1.30128664e-02 2.21370966e+00
  1.33034942e+00 2.64226527e+00 5.11113619e-01 3.91517011e+00
  9.00368734e-01 2.72254224e-03]
 [1.13763442e-01 2.95324275e-01 8.85063034e-01 8.40939340e-01
  1.30438706e-01 5.72368907e-02 3.24768261e-01 2.62644738e+00
  4.06193747e-01 2.25075145e-05 6.27488227e-01 4.61225118e-02
  7.40402280e-04 1.81992500e-03 4.22017694e-01 3.48103117e-01
  3.23809725e-01 1.74692107e-03 1.27122411e+00 6.12171318e-01
  7.81421756e-03 3.52374067e-01 5.87755307e-01 6.22980732e-02
  9.96518864e-02 5.75351455e-01 1.73925852e-01 3.59836284e-01
  2.18080457e-02 2.53447264e+00 6.50047674e-01 1.32366997e+00
  1.09163759e-01 6.44057295e-02 6.27233588e-01 4.64281849e-01
  4.91216088e-01 1.92032666e-01 6.61409943e-01 1.63723468e+00
  1.77596758e-01 3.63199601e-02 1.85092062e+00 5.18187453e-01
  5.30054644e-02 4.10337340e-02 1.87881797e+00 3.49843270e+00
  9.46209998e-01 6.25471786e-01]
 [4.32128944e-01 5.24163468e-02 1.26091871e-03 1.31414018e+00
  1.59969222e+00 5.06350489e-02 4.94670227e-01 1.11971020e-02
  2.94171092e-01 7.56058178e+00 9.24615803e-01 7.67438699e-02
  4.10271006e+00 3.47582109e+00 5.87543585e-01 1.94171522e-02
  3.17931897e-01 3.79637910e-01 4.89337299e-01 5.32797927e-01
  2.58051089e+00 1.50310595e-01 1.36771210e-01 4.01581205e-02
  6.61506761e+00 4.54675893e-01 1.08401091e+00 9.42933866e-02
  1.75265998e-02 4.48043797e-02 5.92443565e-01 9.03813435e-01
  9.77822483e-03 7.48942235e+00 4.90212398e-01 7.83478607e-03
  1.75818552e+00 1.58269958e-01 5.23542980e-03 5.42442925e+00
  4.24279579e+00 3.54749817e-01 1.60039880e-01 3.35512448e-01
  2.17713093e-01 9.07988122e-04 1.56340883e-02 3.08384052e-02
  2.92286337e-01 2.32855375e-01]
 [4.13691400e-01 8.96031801e-02 3.50869476e+00 3.95854862e-01
  6.34320160e-01 3.38766778e+00 1.13928407e+00 3.82440545e-01
  4.94878542e-01 8.38569073e-01 4.95812957e-02 2.99687449e+00
  2.12962004e-01 6.58473820e-02 1.79110598e+00 2.06527610e-03
  2.76396719e+00 8.85249118e-01 1.51061139e+00 1.21540605e+00
  3.28316926e-02 4.52876565e-02 4.30046574e+00 1.49846408e-01
  2.00557945e+00 4.65564975e-01 1.81167688e-02 4.95760634e-01
  1.85424667e-02 1.41702939e-02 4.73558415e-01 7.61499763e-03
  5.47800391e-01 2.73394508e+00 2.82836592e+00 1.16280931e-01
  2.50806777e-03 2.03708624e-02 8.31615396e-01 2.27190928e+00
  2.44710189e+00 1.70031844e-02 1.54732595e-01 1.81142483e-01
  3.40560602e-01 4.37149694e-02 6.83096839e-01 2.97176088e-01
  1.94670232e-01 3.04163480e+00]]

### Pivot Table

In [21]:
#Determine pivot table
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                       "bar", "bar", "bar", "bar"],
                    "B": ["one", "one", "one", "two", "two",
                          "one", "one", "two", "two"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

In [23]:
df.head(9)

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [25]:
###################################想办法生成以下表格，行为A、B，列为C###################################
table = pivot_table(df, values='D', index=['A', 'B'],
                  columns=['C'], aggfunc=np.sum)


###################################想办法生成以下表格，行为A、B，列为C###################################
table

C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

### Merging dataframes

In [12]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                       index=[0, 1, 2, 3])
    

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                       index=[4, 5, 6, 7])
    

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                       'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                       index=[8, 9, 10, 11])
    
###################################将df1,df2,df3按行拼接到一起，并赋给result###################################
frames = [df1, df2, df3]

result = pd.concat(frames)

###################################将df1,df2,df3按行拼接到一起，并赋给result####################################

print(result)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11